# Importing Pandas

In [34]:
import pandas as pd

# Opening a local csv file

In [35]:
# pandas.read_csv(filepath_or_buffer, *, sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, skip_blank_lines=True, parse_dates=None, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=<no_default>)
df=pd.read_csv('heart_disease_risk_2026.csv')
df

,patient_id,age,sex,resting_bp_systolic,resting_bp_diastolic,cholesterol_total,hdl,ldl,triglycerides,fasting_blood_sugar,...,family_history,smoker_status,alcohol_units_per_week,exercise_minutes_per_week,sleep_hours,stress_score,wearable_owner,daily_steps,diet_quality_score,has_heart_disease
0,1,44,Male,117,74,193,57,106,119,112,...,False,Never,2.9,86,5.4,19.8,True,7731,62.9,0
1,2,57,Male,139,94,185,69,110,35,114,...,False,Never,3.0,132,4.3,45.8,True,2629,74.6,1
2,3,29,Male,128,78,197,52,108,157,95,...,False,Current,3.5,128,5.1,17.7,True,9290,65.7,0
3,4,72,Male,132,86,197,59,104,143,92,...,False,Never,2.7,18,6.8,63.6,True,7373,48.5,1
4,5,62,Female,116,75,154,65,75,104,135,...,True,Former,3.3,24,8.2,58.7,False,6331,47.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,8996,36,Female,108,63,178,68,82,158,96,...,False,Never,13.0,306,8.6,51.1,False,7144,58.1,0
8996,8997,44,Female,112,73,213,54,139,102,125,...,False,Former,3.4,76,6.5,37.1,False,7395,68.9,0
8997,8998,57,Female,144,93,198,66,113,79,102,...,False,Never,3.9,194,6.2,46.3,False,7424,70.2,0
8998,8999,61,Female,130,70,220,68,135,109,104,...,False,Former,3.9,139,5.0,66.5,False,5716,43.8,1
8999,9000,63,Female,152,104,215,64,117,109,120,...,False,Never,7.3,95,8.8,54.1,False,3860,54.5,0

# Opening CSV Form Url

In [36]:
import requests
from io import StringIO

url="https://raw.githubusercontent.com/Julien-Marcou/Unicode-Emoji/refs/heads/main/unicode-emoji.csv"
headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10:14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req=requests.get(url,headers=headers)
data=StringIO(req.text)

pd.read_csv(data)

,emoji,description,version,keywords,category,group,subgroup,parent,components
0,🏻,light skin tone,1.0,1–2|light|skin|tone|type,components,component,skin-tone,NaN,NaN
1,🏼,medium-light skin tone,1.0,3|medium-light|skin|tone|type,components,component,skin-tone,NaN,NaN
2,🏽,medium skin tone,1.0,4|medium|skin|tone|type,components,component,skin-tone,NaN,NaN
3,🏾,medium-dark skin tone,1.0,5|medium-dark|skin|tone|type,components,component,skin-tone,NaN,NaN
4,🏿,dark skin tone,1.0,6|dark|skin|tone|type,components,component,skin-tone,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3948,🇿🇲,flag: Zambia,2.0,flag,flags,flags,country-flag,NaN,NaN
3949,🇿🇼,flag: Zimbabwe,2.0,flag,flags,flags,country-flag,NaN,NaN
3950,🏴󠁧󠁢󠁥󠁮󠁧󠁿,flag: England,5.0,flag,flags,flags,subdivision-flag,NaN,NaN
3951,🏴󠁧󠁢󠁳󠁣󠁴󠁿,flag: Scotland,5.0,flag,flags,flags,subdivision-flag,NaN,NaN
3952,🏴󠁧󠁢󠁷󠁬󠁳󠁿,flag: Wales,5.0,flag,flags,flags,subdivision-flag,NaN,NaN

# Sep Parameter

In [37]:
pd.read_csv("demo_mlexpec.tsv",sep="\t")
# pd.read_csv("demo_mlexpec.tsv",sep="\t",names=['',''])

,"unit,sex,age,geo\time",2021,2020,2019,2018,2017,2016,2015,2014,2013,...,1969,1968,1967,1966,1965,1964,1963,1962,1961,1960
0,"YR,F,Y1,AL",:,79.4,80.4,80.2,79.7,79.8,79.2,79.8,79.6,...,:,:,:,:,:,:,:,:,:,:
1,"YR,F,Y1,AM",:,:,79.1,79.2,78.5,78.0,77.9,:,:,...,:,:,:,:,:,:,:,:,:,:
2,"YR,F,Y1,AT",:,82.9,83.5,83.3,83.2,83.4,83.0,83.3,83.0,...,:,:,:,:,:,:,:,:,:,:
3,"YR,F,Y1,AZ",:,:,78.6,78.1,77.7,:,77.5,77.0,76.9,...,:,:,:,:,:,:,:,:,:,:
4,"YR,F,Y1,BE",:,82.3,83.6,83.2,83.2,83.2,82.6,83.1,82.5,...,74.4,74.3,74.7,74.4,74.3,74.6,73.9,74.0,74.5,73.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14443,"YR,T,Y_LT1,SM",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
14444,"YR,T,Y_LT1,TR",:,:,79.1,78.9,78.5,78.1,78.2,78.1,78.2,...,:,:,:,:,:,:,:,:,:,:
14445,"YR,T,Y_LT1,UA",:,:,73.4,73.2,73.3,72.9,72.5,71.8,:,...,:,:,:,:,:,:,:,:,:,:
14446,"YR,T,Y_LT1,UK",:,:,:,81.3,81.3,81.2,81.0,81.4,81.1,...,:,:,:,:,:,:,:,:,:,:
14447,"YR,T,Y_LT1,XK",:,:,:,:,:,78.6 p,:,:,:,...,:,:,:,:,:,:,:,:,:,:

# Index col Parameter

In [38]:
pd.read_csv('heart_disease_risk_2026.csv',index_col='patient_id')

,age,sex,resting_bp_systolic,resting_bp_diastolic,cholesterol_total,hdl,ldl,triglycerides,fasting_blood_sugar,hba1c,...,family_history,smoker_status,alcohol_units_per_week,exercise_minutes_per_week,sleep_hours,stress_score,wearable_owner,daily_steps,diet_quality_score,has_heart_disease
patient_id,,,,,,,,,,,,,,,,,,,,,
1,44,Male,117,74,193,57,106,119,112,5.2,...,False,Never,2.9,86,5.4,19.8,True,7731,62.9,0
2,57,Male,139,94,185,69,110,35,114,5.9,...,False,Never,3.0,132,4.3,45.8,True,2629,74.6,1
3,29,Male,128,78,197,52,108,157,95,5.5,...,False,Current,3.5,128,5.1,17.7,True,9290,65.7,0
4,72,Male,132,86,197,59,104,143,92,4.8,...,False,Never,2.7,18,6.8,63.6,True,7373,48.5,1
5,62,Female,116,75,154,65,75,104,135,6.2,...,True,Former,3.3,24,8.2,58.7,False,6331,47.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8996,36,Female,108,63,178,68,82,158,96,5.3,...,False,Never,13.0,306,8.6,51.1,False,7144,58.1,0
8997,44,Female,112,73,213,54,139,102,125,5.9,...,False,Former,3.4,76,6.5,37.1,False,7395,68.9,0
8998,57,Female,144,93,198,66,113,79,102,5.7,...,False,Never,3.9,194,6.2,46.3,False,7424,70.2,0
8999,61,Female,130,70,220,68,135,109,104,5.5,...,False,Former,3.9,139,5.0,66.5,False,5716,43.8,1
9000,63,Female,152,104,215,64,117,109,120,5.0,...,False,Never,7.3,95,8.8,54.1,False,3860,54.5,0

# Header Parameter

In [ ]:
pd.read_csv('heart_disease_risk_2026.csv',header=1)

# UseCol Parameters

In [40]:
pd.read_csv('heart_disease_risk_2026.csv',usecols=['sex','age','patient_id'])

      patient_id  age     sex
0              1   44    Male
1              2   57    Male
2              3   29    Male
3              4   72    Male
4              5   62  Female
...          ...  ...     ...
8995        8996   36  Female
8996        8997   44  Female
8997        8998   57  Female
8998        8999   61  Female
8999        9000   63  Female

[9000 rows x 3 columns]

# Squeeze Parameters

In [41]:
df=pd.read_csv('heart_disease_risk_2026.csv',usecols=['sex'])
Series=df.squeeze()
Series

0         Male
1         Male
2         Male
3         Male
4       Female
         ...
8995    Female
8996    Female
8997    Female
8998    Female
8999    Female
Name: sex, Length: 9000, dtype: str

# Skipsrows/nrows Parameters

In [43]:
pd.read_csv('heart_disease_risk_2026.csv',skiprows=[1,2])

,patient_id,age,sex,resting_bp_systolic,resting_bp_diastolic,cholesterol_total,hdl,ldl,triglycerides,fasting_blood_sugar,...,family_history,smoker_status,alcohol_units_per_week,exercise_minutes_per_week,sleep_hours,stress_score,wearable_owner,daily_steps,diet_quality_score,has_heart_disease
0,3,29,Male,128,78,197,52,108,157,95,...,False,Current,3.5,128,5.1,17.7,True,9290,65.7,0
1,4,72,Male,132,86,197,59,104,143,92,...,False,Never,2.7,18,6.8,63.6,True,7373,48.5,1
2,5,62,Female,116,75,154,65,75,104,135,...,True,Former,3.3,24,8.2,58.7,False,6331,47.3,1
3,6,50,Female,122,71,147,46,101,41,134,...,True,Former,3.3,190,5.9,55.1,False,6857,82.6,0
4,7,50,Female,133,85,227,63,124,194,109,...,False,Never,5.1,91,8.2,82.2,True,8466,63.7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8993,8996,36,Female,108,63,178,68,82,158,96,...,False,Never,13.0,306,8.6,51.1,False,7144,58.1,0
8994,8997,44,Female,112,73,213,54,139,102,125,...,False,Former,3.4,76,6.5,37.1,False,7395,68.9,0
8995,8998,57,Female,144,93,198,66,113,79,102,...,False,Never,3.9,194,6.2,46.3,False,7424,70.2,0
8996,8999,61,Female,130,70,220,68,135,109,104,...,False,Former,3.9,139,5.0,66.5,False,5716,43.8,1
8997,9000,63,Female,152,104,215,64,117,109,120,...,False,Never,7.3,95,8.8,54.1,False,3860,54.5,0

In [45]:
pd.read_csv('heart_disease_risk_2026.csv',nrows=100)

,patient_id,age,sex,resting_bp_systolic,resting_bp_diastolic,cholesterol_total,hdl,ldl,triglycerides,fasting_blood_sugar,...,family_history,smoker_status,alcohol_units_per_week,exercise_minutes_per_week,sleep_hours,stress_score,wearable_owner,daily_steps,diet_quality_score,has_heart_disease
0,1,44,Male,117,74,193,57,106,119,112,...,False,Never,2.9,86,5.4,19.8,True,7731,62.9,0
1,2,57,Male,139,94,185,69,110,35,114,...,False,Never,3.0,132,4.3,45.8,True,2629,74.6,1
2,3,29,Male,128,78,197,52,108,157,95,...,False,Current,3.5,128,5.1,17.7,True,9290,65.7,0
3,4,72,Male,132,86,197,59,104,143,92,...,False,Never,2.7,18,6.8,63.6,True,7373,48.5,1
4,5,62,Female,116,75,154,65,75,104,135,...,True,Former,3.3,24,8.2,58.7,False,6331,47.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,80,Male,121,79,289,66,178,263,143,...,False,Current,1.9,229,5.8,53.7,True,7844,78.6,0
96,97,49,Male,127,79,182,58,55,314,97,...,False,Current,33.2,181,4.1,49.6,False,7520,49.5,0
97,98,57,Male,140,79,150,41,79,193,178,...,True,Never,5.1,86,7.8,81.9,True,8197,54.8,1
98,99,40,Male,135,73,247,61,149,176,104,...,True,Former,2.6,189,8.3,33.4,False,5398,62.4,0
99,100,40,Female,129,76,210,51,110,279,95,...,False,Former,19.2,94,6.5,57.4,False,6911,41.8,0

# Encoding Parameter

In [46]:
pd.read_csv('heart_disease_risk_2026.csv',encoding='utf-8')#latin-01,etc

,patient_id,age,sex,resting_bp_systolic,resting_bp_diastolic,cholesterol_total,hdl,ldl,triglycerides,fasting_blood_sugar,...,family_history,smoker_status,alcohol_units_per_week,exercise_minutes_per_week,sleep_hours,stress_score,wearable_owner,daily_steps,diet_quality_score,has_heart_disease
0,1,44,Male,117,74,193,57,106,119,112,...,False,Never,2.9,86,5.4,19.8,True,7731,62.9,0
1,2,57,Male,139,94,185,69,110,35,114,...,False,Never,3.0,132,4.3,45.8,True,2629,74.6,1
2,3,29,Male,128,78,197,52,108,157,95,...,False,Current,3.5,128,5.1,17.7,True,9290,65.7,0
3,4,72,Male,132,86,197,59,104,143,92,...,False,Never,2.7,18,6.8,63.6,True,7373,48.5,1
4,5,62,Female,116,75,154,65,75,104,135,...,True,Former,3.3,24,8.2,58.7,False,6331,47.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,8996,36,Female,108,63,178,68,82,158,96,...,False,Never,13.0,306,8.6,51.1,False,7144,58.1,0
8996,8997,44,Female,112,73,213,54,139,102,125,...,False,Former,3.4,76,6.5,37.1,False,7395,68.9,0
8997,8998,57,Female,144,93,198,66,113,79,102,...,False,Never,3.9,194,6.2,46.3,False,7424,70.2,0
8998,8999,61,Female,130,70,220,68,135,109,104,...,False,Former,3.9,139,5.0,66.5,False,5716,43.8,1
8999,9000,63,Female,152,104,215,64,117,109,120,...,False,Never,7.3,95,8.8,54.1,False,3860,54.5,0

# Skip bad lines

In [54]:
pd.read_csv('heart_disease_risk_2026.csv',skip_blank_lines=True)

,patient_id,age,sex,resting_bp_systolic,resting_bp_diastolic,cholesterol_total,hdl,ldl,triglycerides,fasting_blood_sugar,...,family_history,smoker_status,alcohol_units_per_week,exercise_minutes_per_week,sleep_hours,stress_score,wearable_owner,daily_steps,diet_quality_score,has_heart_disease
0,1,44,Male,117,74,193,57,106,119,112,...,False,Never,2.9,86,5.4,19.8,True,7731,62.9,0
1,2,57,Male,139,94,185,69,110,35,114,...,False,Never,3.0,132,4.3,45.8,True,2629,74.6,1
2,3,29,Male,128,78,197,52,108,157,95,...,False,Current,3.5,128,5.1,17.7,True,9290,65.7,0
3,4,72,Male,132,86,197,59,104,143,92,...,False,Never,2.7,18,6.8,63.6,True,7373,48.5,1
4,5,62,Female,116,75,154,65,75,104,135,...,True,Former,3.3,24,8.2,58.7,False,6331,47.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,8996,36,Female,108,63,178,68,82,158,96,...,False,Never,13.0,306,8.6,51.1,False,7144,58.1,0
8996,8997,44,Female,112,73,213,54,139,102,125,...,False,Former,3.4,76,6.5,37.1,False,7395,68.9,0
8997,8998,57,Female,144,93,198,66,113,79,102,...,False,Never,3.9,194,6.2,46.3,False,7424,70.2,0
8998,8999,61,Female,130,70,220,68,135,109,104,...,False,Former,3.9,139,5.0,66.5,False,5716,43.8,1
8999,9000,63,Female,152,104,215,64,117,109,120,...,False,Never,7.3,95,8.8,54.1,False,3860,54.5,0

# D types parameter

In [59]:
pd.read_csv('heart_disease_risk_2026.csv',dtype={'resting_bp_systolic':int})

,patient_id,age,sex,resting_bp_systolic,resting_bp_diastolic,cholesterol_total,hdl,ldl,triglycerides,fasting_blood_sugar,...,family_history,smoker_status,alcohol_units_per_week,exercise_minutes_per_week,sleep_hours,stress_score,wearable_owner,daily_steps,diet_quality_score,has_heart_disease
0,1,44,Male,117,74,193,57,106,119,112,...,False,Never,2.9,86,5.4,19.8,True,7731,62.9,0
1,2,57,Male,139,94,185,69,110,35,114,...,False,Never,3.0,132,4.3,45.8,True,2629,74.6,1
2,3,29,Male,128,78,197,52,108,157,95,...,False,Current,3.5,128,5.1,17.7,True,9290,65.7,0
3,4,72,Male,132,86,197,59,104,143,92,...,False,Never,2.7,18,6.8,63.6,True,7373,48.5,1
4,5,62,Female,116,75,154,65,75,104,135,...,True,Former,3.3,24,8.2,58.7,False,6331,47.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,8996,36,Female,108,63,178,68,82,158,96,...,False,Never,13.0,306,8.6,51.1,False,7144,58.1,0
8996,8997,44,Female,112,73,213,54,139,102,125,...,False,Former,3.4,76,6.5,37.1,False,7395,68.9,0
8997,8998,57,Female,144,93,198,66,113,79,102,...,False,Never,3.9,194,6.2,46.3,False,7424,70.2,0
8998,8999,61,Female,130,70,220,68,135,109,104,...,False,Former,3.9,139,5.0,66.5,False,5716,43.8,1
8999,9000,63,Female,152,104,215,64,117,109,120,...,False,Never,7.3,95,8.8,54.1,False,3860,54.5,0

# Handling dates

In [ ]:
pd.read_csv('IPl Matches 2008-2020.csv',parse_dates=['dates']).info()

# Converters

In [65]:
def rename(name):
    if(name=='Male'):
        return 'male'
    else:
        return name

In [66]:
rename('Male')

'male'

In [67]:
pd.read_csv('heart_disease_risk_2026.csv',converters={'sex':rename})

,patient_id,age,sex,resting_bp_systolic,resting_bp_diastolic,cholesterol_total,hdl,ldl,triglycerides,fasting_blood_sugar,...,family_history,smoker_status,alcohol_units_per_week,exercise_minutes_per_week,sleep_hours,stress_score,wearable_owner,daily_steps,diet_quality_score,has_heart_disease
0,1,44,male,117,74,193,57,106,119,112,...,False,Never,2.9,86,5.4,19.8,True,7731,62.9,0
1,2,57,male,139,94,185,69,110,35,114,...,False,Never,3.0,132,4.3,45.8,True,2629,74.6,1
2,3,29,male,128,78,197,52,108,157,95,...,False,Current,3.5,128,5.1,17.7,True,9290,65.7,0
3,4,72,male,132,86,197,59,104,143,92,...,False,Never,2.7,18,6.8,63.6,True,7373,48.5,1
4,5,62,Female,116,75,154,65,75,104,135,...,True,Former,3.3,24,8.2,58.7,False,6331,47.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,8996,36,Female,108,63,178,68,82,158,96,...,False,Never,13.0,306,8.6,51.1,False,7144,58.1,0
8996,8997,44,Female,112,73,213,54,139,102,125,...,False,Former,3.4,76,6.5,37.1,False,7395,68.9,0
8997,8998,57,Female,144,93,198,66,113,79,102,...,False,Never,3.9,194,6.2,46.3,False,7424,70.2,0
8998,8999,61,Female,130,70,220,68,135,109,104,...,False,Former,3.9,139,5.0,66.5,False,5716,43.8,1
8999,9000,63,Female,152,104,215,64,117,109,120,...,False,Never,7.3,95,8.8,54.1,False,3860,54.5,0

# na_values parameters

In [68]:
pd.read_csv('heart_disease_risk_2026.csv',na_values=['Female'])

,patient_id,age,sex,resting_bp_systolic,resting_bp_diastolic,cholesterol_total,hdl,ldl,triglycerides,fasting_blood_sugar,...,family_history,smoker_status,alcohol_units_per_week,exercise_minutes_per_week,sleep_hours,stress_score,wearable_owner,daily_steps,diet_quality_score,has_heart_disease
0,1,44,Male,117,74,193,57,106,119,112,...,False,Never,2.9,86,5.4,19.8,True,7731,62.9,0
1,2,57,Male,139,94,185,69,110,35,114,...,False,Never,3.0,132,4.3,45.8,True,2629,74.6,1
2,3,29,Male,128,78,197,52,108,157,95,...,False,Current,3.5,128,5.1,17.7,True,9290,65.7,0
3,4,72,Male,132,86,197,59,104,143,92,...,False,Never,2.7,18,6.8,63.6,True,7373,48.5,1
4,5,62,NaN,116,75,154,65,75,104,135,...,True,Former,3.3,24,8.2,58.7,False,6331,47.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,8996,36,NaN,108,63,178,68,82,158,96,...,False,Never,13.0,306,8.6,51.1,False,7144,58.1,0
8996,8997,44,NaN,112,73,213,54,139,102,125,...,False,Former,3.4,76,6.5,37.1,False,7395,68.9,0
8997,8998,57,NaN,144,93,198,66,113,79,102,...,False,Never,3.9,194,6.2,46.3,False,7424,70.2,0
8998,8999,61,NaN,130,70,220,68,135,109,104,...,False,Former,3.9,139,5.0,66.5,False,5716,43.8,1
8999,9000,63,NaN,152,104,215,64,117,109,120,...,False,Never,7.3,95,8.8,54.1,False,3860,54.5,0

# Load a Huge dataset in Chunks

In [70]:
df=pd.read_csv('heart_disease_risk_2026.csv',chunksize=1000)
for chunks in df:
    print(chunks.shape)

(1000, 27)
(1000, 27)
(1000, 27)
(1000, 27)
(1000, 27)
(1000, 27)
(1000, 27)
(1000, 27)
(1000, 27)